#!/bin/bash

set -e

echo "Activate venv..."
source .venv/bin/activate
echo "Venv activated successfully"

ruff format . --check
echo "Ruff formatter passed."

ruff check . 
echo "Ruff linter passed."

mypy .
echo "Mypy passed."

pyright .
echo "Pyright passed."

pytest .
echo "Pytest passed."
