#!/bin/bash

set -e

echo "Activating virtual environment..."
source .venv/bin/activate

echo "Running ruff formatter..."
ruff format . --check

echo "Running ruff linter..."
ruff check . 

echo "Running mypy..."
mypy .

echo "Running pyright..."
pyright .

echo "Running pytest..."
pytest .
